version: '3.3'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: no
    volumes:
      - redis_stack_volume_data:/data
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  redis_stack_volume_data:
