services:
  redis:
    # latest version installed: 7.2.4
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: no
    volumes:
      - redis_stack_volume_data:/data
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS=--save 900 1 300 10 60 100 --rdbcompression yes --appendonly yes --appendfsync everysec --user admin on >p4ss ~* &* +@all

volumes:
  redis_stack_volume_data:
